# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Recipes
email: andrew.mehrmann@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Public webpage so I can easily access my recipes from anywhere.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dkmehrmann.github.io/recipes/" # the base hostname & protocol for your site
twitter_username: andrewmehrmann
github_username:  dkmehrmann

# Build settings
markdown: kramdown
